<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="hardver.css">
    <link rel="stylesheet" href="header.css">
    <link rel="stylesheet" href="zaszlok.css">
</head>
<body>
<?php $header = file_get_contents("./header.html"); echo $header; ?>
<!-- ######### CONTENT #########-->
<div><a href="harver.php"><img src="mzaszlo.png" alt="Magyar" title="Magyar" class="zaszlok"></a></div>
<div id="content">
    <h1 align="center">Hardware Requirements</h1>
    <h2 align="left">System Specifications for Employees</h2>
    <p>This page specifies the hardware requirements planned for the company so far, which includes everything from employees' computers and servers to the bridge router.</p>
    <div style="height: 5vh;" class="empty-space"></div>
    <p>For the smoothest possible workflow for employees, a high-end system has been specified, which is shown below:</p>
    <table class="container-table">
        <tr>
            <td><p><img src="./be quiet 802.png" alt="worket pc case" class="img-restrict"></p></td>
            <td><table id="personal-table" class="tables">
                <tr>
                    <td class="component-name">Computer Case</td>
                    <td class="spec">Cooler Master MasterCase H500P Mesh + 2x Noctua NF-A20 PWM</td>
                </tr>
                <tr>
                    <td class="component-name">Fans</td>
                    <td class="spec">3x Noctua NF-A14 PWM per Case</td>
                </tr>
                <tr>
                    <td class="component-name">CPU Cooler</td>
                    <td class="spec">NH-D15 NM-AM4 with mounting kit</td>
                </tr>
                <tr>
                    <td class="component-name">Motherboard</td>
                    <td class="spec">ASRock WRX80 Creator R2.0</td>
                </tr>
                <tr>
                    <td class="component-name">Processor</td>
                    <td class="spec">Ryzen Threadripper PRO 5965WX</td>
                </tr>
                <tr>
                    <td class="component-name">Memory</td>
                    <td class="spec">G.SKILL Ripjaws V 64GB (4x16GB) - DDR4 4400MHz F4-4400C19D-32GVK x2</td>
                </tr>
                <tr>
                    <td class="component-name">Graphics Card</td>
                    <td class="spec">RTX A6000 Ada</td>
                </tr>
                <tr>
                    <td class="component-name">Storage</td>
                    <td class="spec">Samsung 970 EVO Plus 2TB x 5</td>
                </tr>
                <tr>
                    <td class="component-name">Power Supply</td>
                    <td class="spec">Corsair HX1200 1200W Platinum per PC<br>and 2x Legrand DAKER DK PLUS 5000VA UPS</td>
                </tr>
                <tr>
                    <td>Keyboard</td>
                    <td>Redragon Kumara 2 (K552-2_BROWN_HU)</td>
                </tr>
                <tr>
                    <td>Mouse</td>
                    <td>SteelSeries Arctis 7p+</td>
                </tr>
            </table></td>
        <tr>
            <td colspan="2"><p id="spec-paragraph-restrict">The components have been assembled to provide the highest performance with minimal noise. Since there will be 10+ computers in close proximity in the office, it was considered important to minimize the noise generated by the machines.</p></td></tr>
        </tr>
    </table>
    <div style="height: 5vh;" class="empty-space"></div>
    <h2 align="left">List of Network Devices</h2>
    <p>The following devices constitute the entire network. The network is divided into 3 subnets and interconnected redundantly. Cooling for the server room has not been specified due to lack of information about the room.</p>
    <table class="container-table">
        <tr>
            <td><p><img src="./ftp-server.png" alt="dell-poweredge-r630 server" class="img-restrict"></p></td>
            <td><table id="network-table" class="tables">
                <tr>
                    <td class="component-name">Routers</td>
                    <td>4x Cisco C891F-K9 Router</td>
                </tr>
                <tr>
                    <td class="component-name">Switches</td>
                    <td>2x Cisco CBS220-24P-4G-EU</td>
                </tr>
                <tr>
                    <td rowspan="3" class="component-name">Servers</td>
                    <td>FTP Server with 10Gbps Bandwidth<br>128GB 2400MHz RAM<br>128TB 12Gbps SAS Storage (hardware RAID)<br>Xeon E5-2673 V4<br>AMD EPYC High Performance Computing Server with SAS/M.2 drives 16/32x DIMMs 10GBe port, minimum 2GPU</td> <!--https://www.bargainhardware.co.uk/dell-poweredge-r630-8-sff-configure-to-order-->
                </tr>
                <tr>
                    <td>Server with HTTP, DNS, and DHCP Services</td>
                </tr>
                <tr>
                    <td>HPC Server (Consultation required)</td>
                </tr>
                <tr>
                    <td>Multi-layer switches</td>
                    <td>4x Cisco C9200L-48T-4G-E</td>
                </tr>
                <tr>
                    <td>Printers</td>
                    <td>HP LaserJet Enterprise M652dn (J7Z99A)</td>
                </tr>
                <tr>
                    <td>Soho router</td>
                    <td>ASUS ZenWiFi Pro XT12 (1-Pack) Router</td>
                </tr>
                <tr>
                    <td>Cables</td>
                    <td>Dependent on the area</td>
                </tr>
            </table></td>
        </tr>
    </table>
    
    <div style="height: 5vh;" class="empty-space"></div>
    <p>
    </p>
</div>
<!-- ######### CONTENT ######### -->
</body>
</html>